### ISSUE TITLE
Bug: Erstellen einer Gruppe mit Token

### ISSUE THREAD

**Issue by MrzJkl** [DennyGDeChef/wertung#3]
# BUGREPORT
Hallo zusammen, 

beim Erstellen einer Gruppe mit einem Token ist mir aufgefallen, dass dort als Unterüberschrift folgendes steht: **01.01.1970 , ()**

![grafik](https://user-images.githubusercontent.com/38078338/56084225-47598100-5e30-11e9-8a53-bc3ea51d4b43.png)

**Comment by DennyGDeChef** [comment]
Ups... durch das Einfügen der Rollen und Rechte ging das wohl kaputt...
